update

diff --git a/apps/backend/springboot/makefile b/apps/backend/springboot/makefile
--- a/apps/backend/springboot/makefile
+++ b/apps/backend/springboot/makefile
@@ -6,16 +6,22 @@ run:
 	else \
 		./mvnw spring-boot:run; \
 	fi
+
 clean:
 	@mvn clean -s ./settings.xml
+
 test:
 	@mvn test -s ./settings.xml
+
 package:
 	@mvn package -s ./settings.xml
+
 install:
 	@mvn clean install -s ./settings.xml
+
 startDev:
 	@mvn spring-boot:run -s ./settings.xml
+
 startSpringbootDocker:
 	@vlt run --command="make -f makefile.ci startSpringbootDocker"
 
@@ -26,7 +32,7 @@ testAwsConnected:
 	@vlt run --command="aws s3 ls"
 
 awsECRLogin:
-	@ vlt run --command="aws ecr get-login --region eu-central-1 --no-include-email"
+	@vlt run --command="aws ecr get-login --region eu-central-1 --no-include-email"
 
 createAwsEcrRepo:
 	@vlt run --command="make -f makefile.ci createAwsEcrRepo"
@@ -35,9 +41,8 @@ loginToAwsEcrRepo:
 	@vlt run --command="make -f makefile.ci loginToAwsEcrRepo"
 
 createAwsBeanstalkApplication:
-# Create environment
 	@eb create your-environment-name &&\
-	if [ $? -ne 0 ]; then
-    	echo "Error occurred during environment creation. Terminating environment."
-    	eb terminate your-environment-name -f
+	if [ $? -ne 0 ]; then \
+    	echo "Error occurred during environment creation. Terminating environment." ;\
+    	eb terminate your-environment-name -f ;\
 	fi
